name: Daily Patreon Post

on:
  schedule:
    - cron: "0 9 * * 0,1,6"  # Every Sunday, Monday, and Saturday 12:00 GR
    - cron: "15 14 * * 2"    # Tuesday at 16:15 GR
    - cron: "15 14 * * 5"    # Friday at 17:15 GR
  workflow_dispatch: # Allow manual run

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests selenium pyperclip
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Get Dropbox Access Token
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.DROPBOX_APP_KEY }}:${{ secrets.DROPBOX_APP_SECRET }}" \
            -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} \
            -d grant_type=refresh_token \
            https://api.dropbox.com/oauth2/token)

          echo "Full response: $RESPONSE"
          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

          # Set token as env variable for next steps or calling workflow
          echo "DROPBOX_ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
          
      - name: Run posting script
        env:
          EMAIL: ${{ secrets.PATREON_EMAIL }}
          PASSWORD: ${{ secrets.PATREON_PASS }}
        run: python post_on_patreon.py
