name: Predictions Pipeline

on:
  schedule:
    - cron: "0 17 * * 2" # Tuesday at 16:00 UTC (17:00 British)
    - cron: "0 17 * * 5" # Friday at 17:00 UTC (18:00 British)
  workflow_dispatch: # Allow manual run

jobs:
  majorleague:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Folders
        run: mkdir -p predictions_data/ logs/simu/

      - name: Run Major League Predictions
        run: python majorleague_predictions.py

      - name: Upload Major League predictions
        uses: actions/upload-artifact@v3
        with:
          name: majorleague-predictions
          path: predictions_data/*

  minorleague:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Folders
        run: mkdir -p predictions_data/ logs/simu/

      - name: Run Minor League Predictions
        run: python minorleague_predictions.py

      - name: Upload Minor League predictions
        uses: actions/upload-artifact@v3
        with:
          name: minorleague-predictions
          path: predictions_data/*

  merge_and_tier:
    runs-on: ubuntu-latest
    needs: [majorleague, minorleague]  # Waits for both
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Folders
        run: mkdir -p logs/data/ logs/merger/ predictions_data/ publish/

      - name: Download Major League predictions
        uses: actions/download-artifact@v3
        with:
          name: majorleague-predictions
          path: predictions_data/

      - name: Download Minor League predictions
        uses: actions/download-artifact@v3
        with:
          name: minorleague-predictions
          path: predictions_data/

      - name: Merge Predictions
        run: python predictions_merger.py

      - name: Tier Predictions
        run: python predictions_tier.py

      - name: Upload Predictions
        uses: actions/upload-artifact@v3
        with:
          name: predictions
          path: publish/*        

  posting:
    runs-on: ubuntu-latest
    needs: [merge_and_tier]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Get Dropbox Access Token
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.DROPBOX_APP_KEY }}:${{ secrets.DROPBOX_APP_SECRET }}" \
            -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }} \
            -d grant_type=refresh_token \
            https://api.dropbox.com/oauth2/token)

          echo "Full response: $RESPONSE"
          ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')

          # Set token as env variable for next steps or calling workflow
          echo "DROPBOX_ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Create Folders
        run: mkdir -p publish/

      - name: Download  predictions
        uses: actions/download-artifact@v3
        with:
          name: predictions
          path: publish/

      - name: Upload_to_dropbox
        run: python upload_to_dropbox.py
